spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: productService
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/api/product/**

            - id: orderService
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/api/order/**,/api/cart/**

            - id: userService
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/user/**

            - id: eurekaServer
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/main
              filters:
                - SetPath=/

            - id: eurekaServerStatic
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"