spring:
  datasource:
    url: ${ORDER_SERVICE_DB_URL}
    username: ${ORDER_SERVICE_DB_USERNAME}
    password: ${ORDER_SERVICE_DB_PASSWORD}
  jpa:
    show-sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}
    listener:
      simple:
        missing-queues-fatal: false
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          group: ecom-order-service-group
Eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
server:
  port: 8083
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
app:
  message: "Hello order service"
logging:
  file:
    name: logs/orderService.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB

#Ressilence4j

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      productService:
        maxAttempts: 5
        waitDuration: 1000

  ratelimiter:
    instances:
      rateKiller:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0

