spring:
  mongodb:
    database: ${USER_SERVICE_DB}
    uri: ${USER_SERVICE_DB_URI}
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}
    listener:
      simple:
        missing-queues-fatal: false
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          group: ecom-user-service-group
server:
  port: 8082
Eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: logs/userService.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB


app:
  message: "Hello from User Service"
