spring:
  application:
    name: Ecom-Config-Server
  profiles:
    active: native
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PASSWORD:guest}
    virtual-host: ${RMQ_VIRTUAL_HOST:/}
    listener:
      simple:
        missing-queues-fatal: false
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          group: ecom-config-server-group
    config:
      server:
        native:
          search-locations: file:///${CONFIG_FILE_PATH}
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

